### ISSUE TITLE
ДЗ3 -1. Невірний запит

### ISSUE THREAD

**Issue by amaneshi** [timgas/funnyNirvana#14]
Це єдиний запит до якого є суттєві претензії. Тут треба знайти суму грошей для кожного користувача, незалежно від валюти (зсумувати кошти на усіх рахунках користувача) і повернути користувачів в яких більше 1000.
Також є побажання - я говорив що коли пишеш запит для декількох таблиць то краще використовувати псевдоніми.

https://github.com/timgas/funnyNirvana/blob/1c862dfe609d2c4eb02037b859ebc97cd3d28253/PHP/SQL/Command%20SQL.txt#L10

**Comment by timgas** [comment]
SELECT user_id, name AS user_name, SUM(balance) AS totalSum
FROM users
LEFT JOIN accounts
ON	users.id = accounts.user_id
GROUP	BY user_id, NAME
HAVING totalSum > 1000;

**Comment by timgas** [comment]
> SELECT user_id, name AS user_name, SUM(balance) AS totalSum
> FROM users
> LEFT JOIN accounts
> ON users.id = accounts.user_id
> GROUP BY user_id, NAME
> HAVING totalSum > 1000;
